### ISSUE TITLE
Add a timer 

### ISSUE THREAD

**Issue by Prune11** [HugoOjvindFrancois/ojvindix#1]
As a ojvindix user
I want a timer to start when I enter my first word and stop when I enter the answer
So that I can know how long it took me to find the word

**Comment by mnosov622** [comment]
Hi @Prune11 !

I would love to work on this issue. Could you assign it to me, please ?

**Comment by webdev69420** [comment]
+1

**Comment by Prune11** [comment]
> Hi @Prune11 !
> 
> I would love to work on this issue. Could you assign it to me, please ?

Hi @mnosov622, you'd have to ask @HugoOjvindFrancois the main Dev of the app if it's ok !

**Comment by webdev69420** [comment]
@HugoOjvindFrancois thanks for giving this guy permission to work on Ojvindix! We have a French saying that perfectly applies to this situation imo: "Plus on est de fous, plus on rit."!

**Comment by webdev69420** [comment]
@mnosov622 feel free to fork this repo, add the timer functionnality and then create a pull request so we can add your changes! 🙂

**Comment by HugoOjvindFrancois** [comment]
We're late on schedule, so I will assign this issue to someone else, sry
