### ISSUE TITLE
Multiplayer soon?

### ISSUE THREAD

**Issue by webdev69420** [HugoOjvindFrancois/ojvindix#3]
I'd like to play this awesome game with my friends, could you make this work?
I don't care about the specifics or about how you plan to integrate this feature, just let me play with my buddies plz
Thanks :)

**Comment by HugoOjvindFrancois** [comment]
Hi @webdev69420, could you please specify how you want to play multiplayer with your friends ? Otherwise I would make something you might not enjoy at all.

Thanks for taking interest in the project !!

**Comment by webdev69420** [comment]
Please just rip off the multiplayer system from this game: [https://cemantix.certitudes.org/](https://cemantix.certitudes.org/)

**Comment by HugoOjvindFrancois** [comment]
What do you like about those multiplayer features that you want in Ojvindix ? Or maybe features that was missing and you want in Ojvindix
