### ISSUE TITLE
Epic battle mode

### ISSUE THREAD

**Issue by Pop115** [HugoOjvindFrancois/ojvindix#5]
As an ojvindix user, I want to have epic battles with my friends when searching for the word of the day, doom music shall be playing as I lay waste on my keyboard

A library that can be used is https://socket.io/

I want epic sound and animation of explosions when another user enter a word
Writing multiple good words in a row allow to make a combo, once the combo is high enough (3?), doom music should start playing and blood shall pour on the user interface
When the word of the day is found, epic explosion again and name of the winner written with doom font shall appear on the screen of everyone

**Comment by webdev69420** [comment]
Currently thinking about how to implement the features below:

- Blood pouring on the UI
- Explosion (+ name of the winner) when the user wins

I'll keep you guys posted when I start implementing those features and when I'm finished!
